spring:
  config:
    import: optional:file:env.properties
  main:
    banner-mode: log
  ai:
    openai:
      api-key: ${AZURE_OPENAI_API_KEY}
      base-url: ${AZURE_OPENAI_ENDPOINT}
      chat:
        model: ${AZURE_OPENAI_DEPLOYMENT_NAME}
    mcp:
      client:
        name: aster
        initialized: false
        request-timeout: 10m

logging:
  console:
    enabled: ${LOG_CONSOLE:false}
  file:
    name: ${LOG_FILE:.aster/aster.log}
  level:
    dev.mvlcak.aster: ${LOG_LEVEL:INFO}
aster:
  tui:
    app-name: Aster
    tick-rate-ms: 75
    resize-grace-period-ms: 50